name: 'Is Actor a Team Member'

description: 'Checks if the actor is a member of the team'

inputs:
  github-actor:
    required: true
    description: The GitHub actor to check for membership
  github-organization:
    required: true
    description: The GitHub organization to check for membership
  github-team-slugs:
    required: true
    description: The GitHub team slugs to check for membership
  github-token:
    required: true
    description: The GitHub token to use for authentication      

runs:
  using: 'node16'
  main: 'dist/index.js'
